#!/bin/bash

#Update yum and install httpd
yum update -y
yum -y install httpd

#Start the service
systemctl enable httpd.service
systemctl start httpd.service


#Make changes to firewalld
firewall-offline-cmd --add-service=http
systemctl enable firewalld
systemctl restart firewalld

#Update index.html
hostname > /var/www/html/index.html

