#!/bin/bash
 
touch /tmp/executescript 
# cp /etc/motd /etc/motd.bkp
# cat << EOF > /etc/motd
 
# I have been modified by cloud-init at $(date)
 
# EOF

# #Update yum and install httpd
# #yum update -y
# yum -y install httpd

# #Start the service
# systemctl enable httpd.service
# systemctl start httpd.service


# #Make changes to firewalld
# firewall-offline-cmd --add-service=http
# systemctl enable firewalld
# systemctl restart firewalld

# #Update index.html
# hostname > /var/www/html/index.html

